Adding the Workflow File

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -91,61 +91,61 @@ jobs:
         working-directory: ./workspaces/hcp
         run: terraform ${{ github.event.inputs.apply }} -auto-approve -no-color -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="hvn_id=${{ secrets.HVN_ID }}" -var="aws_default_region=${{ secrets.AWS_DEFAULT_REGION }}"
           
-  DeployStg:
-    name: Deploy Vault Cluster
-    runs-on: ubuntu-latest
-    needs: [DeployDev]
-    steps:
-      - name: Checkout Repo
-        uses: actions/checkout@v3
-
-      - name: HashiCorp - Setup Terraform
-        uses: hashicorp/setup-terraform@v2.0.0
-        with:
-          terraform_version: 1.2.2
-          cli_config_credentials_token: ${{ secrets.TFC_API_KEY }}
-          terraform_wrapper: false
-
-      - name: Terraform fmt
-        id: fmt
-        working-directory: ./workspaces/vault_provision
-        run: terraform fmt -check
-        continue-on-error: true
-
-      - name: Terraform Init
-        id: init
-        working-directory: ./workspaces/vault_provision
-        run: terraform init
-
-      - name: Terraform Validate
-        id: validate
-        working-directory: ./workspaces/vault_provision
-        run: terraform validate -no-color
-
-      - name: Terraform Plan
-        id: plan
-        working-directory: ./workspaces/vault_provision
-        run: terraform ${{ github.event.inputs.plan }} -no-color -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="tier=dev" -var="vault_cluster_id=${{ secrets.VAULT_CLUSTER_ID }}"
-        continue-on-error: false
-
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        working-directory: ./workspaces/vault_provision
-        run: exit 1
-
-      #- name: Terraform Apply
-      #  id: apply
-      #  working-directory: ./workspaces/vault_provision
-      #  run: terraform ${{ github.event.inputs.apply }} -auto-approve -no-color -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="hvn_id=${{ secrets.HVN_ID }}" -var="aws_default_region=${{ secrets.AWS_DEFAULT_REGION }}"
-
-
-  DeployProd:
-    runs-on: ubuntu-latest
-    name: Deploy to Prod
-    needs: [DeployStg]
-    environment:
-      name: Production
-    steps:
-      - uses: actions/checkout@v3
-      - run: |
-          echo ${{ secrets.ENVIRONMENT }} has been Deployed!
+#  DeployStg:
+#    name: Deploy Vault Cluster
+#    runs-on: ubuntu-latest
+#    needs: [DeployDev]
+#    steps:
+#      - name: Checkout Repo
+#        uses: actions/checkout@v3
+#
+#      - name: HashiCorp - Setup Terraform
+#        uses: hashicorp/setup-terraform@v2.0.0
+#        with:
+#          terraform_version: 1.2.2
+#          cli_config_credentials_token: ${{ secrets.TFC_API_KEY }}
+#          terraform_wrapper: false
+#
+#      - name: Terraform fmt
+#        id: fmt
+#        working-directory: ./workspaces/vault_provision
+#        run: terraform fmt -check
+#        continue-on-error: true
+#
+#      - name: Terraform Init
+#        id: init
+#        working-directory: ./workspaces/vault_provision
+#        run: terraform init
+#
+#      - name: Terraform Validate
+#        id: validate
+#        working-directory: ./workspaces/vault_provision
+#        run: terraform validate -no-color
+#
+#      - name: Terraform Plan
+#        id: plan
+#        working-directory: ./workspaces/vault_provision
+#        run: terraform ${{ github.event.inputs.plan }} -no-color -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="tier=dev" -var="vault_cluster_id=${{ secrets.VAULT_CLUSTER_ID }}"
+#        continue-on-error: false
+#
+#      - name: Terraform Plan Status
+#        if: steps.plan.outcome == 'failure'
+#        working-directory: ./workspaces/vault_provision
+#        run: exit 1
+#
+#      - name: Terraform Apply
+#        id: apply
+#        working-directory: ./workspaces/vault_provision
+#        run: terraform ${{ github.event.inputs.apply }} -auto-approve -no-color -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="hvn_id=${{ secrets.HVN_ID }}" -var="aws_default_region=${{ secrets.AWS_DEFAULT_REGION }}"
+#
+#
+#  DeployProd:
+#    runs-on: ubuntu-latest
+#    name: Deploy to Prod
+#    needs: [DeployStg]
+#    environment:
+#      name: Production
+#    steps:
+#      - uses: actions/checkout@v3
+#      - run: |
+#          echo ${{ secrets.ENVIRONMENT }} has been Deployed!
