Adding Environments

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -29,6 +29,32 @@ defaults:
   
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
+  tflint:
+    runs-on: ubuntu-latest
+
+    steps:
+    - uses: actions/checkout@v2
+      name: Checkout source code
+
+    - uses: actions/cache@v2
+      name: Cache plugin dir
+      with:
+        path: ~/.tflint.d/plugins
+        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}
+
+    - uses: terraform-linters/setup-tflint@v1
+      name: Setup TFLint
+      with:
+        tflint_version: v0.29.0
+
+    - name: Show version
+      run: tflint --version
+
+    - name: Init TFLint
+      run: tflint --init
+
+    - name: Run TFLint
+      run: tflint -f compact
   #Lint:
   #  name: Lint Code Base
   #  runs-on: ubuntu-latest
@@ -47,7 +73,7 @@ jobs:
     #if: "contains(github.event.head_commit.message, 'build')"
     name: Deploy HCP
     runs-on: ubuntu-latest
-    #needs: [Lint]
+    needs: [tflint]
     env:
       environment: dev
       work_dir: ./ent-infra-engineering-hcp/workspaces/dev/hcp
@@ -93,62 +119,62 @@ jobs:
         working-directory: ${{ env.work_dir}}
         run: exit 1
 
-      - name: Terraform Apply
-        id: apply
-        working-directory: ${{ env.work_dir }}
-        run: terraform ${{ github.event.inputs.apply }} -auto-approve -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="hvn_id=hv-personal-${{ env.environment }}" -var="aws_default_region=${{ secrets.AWS_DEFAULT_REGION }}"
+#      - name: Terraform Apply
+#        id: apply
+#        working-directory: ${{ env.work_dir }}
+#        run: terraform ${{ github.event.inputs.apply }} -auto-approve -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="hvn_id=hv-personal-${{ env.environment }}" -var="aws_default_region=${{ secrets.AWS_DEFAULT_REGION }}"
 
-  StageHCP:
-    #if: "contains(github.event.head_commit.message, 'build')"
-    name: Deploy HCP
-    needs: [DevHCP]
-    runs-on: ubuntu-latest
-    env:
-      environment: stg
-      work_dir: ./ent-infra-engineering-hcp/workspaces/stg/hcp
-
-    steps:
-      - name: Checkout Repo
-        uses: actions/checkout@v3
-
-      - name: HashiCorp - Setup Terraform
-        uses: hashicorp/setup-terraform@v2.0.0
-        with:
-          terraform_version: 1.2.2
-          cli_config_credentials_token: ${{ secrets.TFC_API_KEY }}
-          terraform_wrapper: false
-
-      - name: Terraform fmt
-        id: fmt
-        working-directory: ${{ env.work_dir }}
-        run: terraform fmt -check
-        continue-on-error: true
-
-      - name: Terraform Init
-        id: init
-        working-directory: ${{ env.work_dir }}
-        run: terraform init
-
-      - name: Terraform Validate
-        id: validate
-        working-directory: ${{ env.work_dir }}
-        run: terraform validate -no-color
-
-      - name: Terraform Plan
-        id: plan
-        working-directory: ${{ env.work_dir }}
-        run: terraform ${{ github.event.inputs.plan }} -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="hvn_id=hv-personal-${{ env.environment }}" -var="aws_default_region=${{ secrets.AWS_DEFAULT_REGION }}"
-        continue-on-error: false
-
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        working-directory: ${{ env.work_dir}}
-        run: exit 1
-
-      - name: Terraform Apply
-        id: apply
-        working-directory: ${{ env.work_dir }}
-        run: terraform ${{ github.event.inputs.apply }} -auto-approve -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="hvn_id=hv-personal-${{ env.environment }}" -var="aws_default_region=${{ secrets.AWS_DEFAULT_REGION }}"
+#  StageHCP:
+#    #if: "contains(github.event.head_commit.message, 'build')"
+#    name: Deploy HCP
+#    needs: [DevHCP]
+#    runs-on: ubuntu-latest
+#    env:
+#      environment: stg
+#      work_dir: ./ent-infra-engineering-hcp/workspaces/stg/hcp
+#
+#    steps:
+#      - name: Checkout Repo
+#        uses: actions/checkout@v3
+#
+#      - name: HashiCorp - Setup Terraform
+#        uses: hashicorp/setup-terraform@v2.0.0
+#        with:
+#          terraform_version: 1.2.2
+#          cli_config_credentials_token: ${{ secrets.TFC_API_KEY }}
+#          terraform_wrapper: false
+#
+#      - name: Terraform fmt
+#        id: fmt
+#        working-directory: ${{ env.work_dir }}
+#        run: terraform fmt -check
+#        continue-on-error: true
+#
+#      - name: Terraform Init
+#        id: init
+#        working-directory: ${{ env.work_dir }}
+#        run: terraform init
+#
+#      - name: Terraform Validate
+#        id: validate
+#        working-directory: ${{ env.work_dir }}
+#        run: terraform validate -no-color
+#
+#      - name: Terraform Plan
+#        id: plan
+#        working-directory: ${{ env.work_dir }}
+#        run: terraform ${{ github.event.inputs.plan }} -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="hvn_id=hv-personal-${{ env.environment }}" -var="aws_default_region=${{ secrets.AWS_DEFAULT_REGION }}"
+#        continue-on-error: false
+#
+#      - name: Terraform Plan Status
+#        if: steps.plan.outcome == 'failure'
+#        working-directory: ${{ env.work_dir}}
+#        run: exit 1
+#
+#      - name: Terraform Apply
+#        id: apply
+#        working-directory: ${{ env.work_dir }}
+#        run: terraform ${{ github.event.inputs.apply }} -auto-approve -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="hvn_id=hv-personal-${{ env.environment }}" -var="aws_default_region=${{ secrets.AWS_DEFAULT_REGION }}"
 
 #  Stg:
 #    name: Deploy Vault Cluster
