Adding Environments

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -73,17 +73,23 @@ jobs:
       - name: Terraform Init
         id: init
         working-directory: ${{ env.work_dir }}
-        run: terraform init
+        run: |
+          terraform init
+          terraform workspace new ${{ env.TF_WORKSPACE }}
 
       - name: Terraform Validate
         id: validate
         working-directory: ${{ env.work_dir }}
-        run: terraform validate -no-color
+        run: |
+          terraform workspace select ${{ env.TF_WORKSPACE }}
+          terraform validate -no-color
 
       - name: Terraform Plan
         id: plan
         working-directory: ${{ env.work_dir }}
-        run: terraform ${{ github.event.inputs.plan }} -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="hvn_id=hv-personal-${{ env.environment }}" -var="aws_default_region=${{ secrets.AWS_DEFAULT_REGION }}"
+        run: |
+          terraform workspace select ${{ env.TF_WORKSPACE }}
+          terraform ${{ github.event.inputs.plan }} -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="hvn_id=hv-personal-${{ env.environment }}" -var="aws_default_region=${{ secrets.AWS_DEFAULT_REGION }}"
         continue-on-error: false
 
       - name: Terraform Plan Status
@@ -91,68 +97,19 @@ jobs:
         working-directory: ${{ env.work_dir}}
         run: exit 1
 
-      - name: Terraform Apply
-        id: apply
-        working-directory: ${{ env.work_dir }}
-        run: terraform ${{ github.event.inputs.apply }} -auto-approve -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="hvn_id=hv-personal-${{ env.environment }}" -var="aws_default_region=${{ secrets.AWS_DEFAULT_REGION }}"
+#      - name: Terraform Apply
+#        id: apply
+#        working-directory: ${{ env.work_dir }}
+#        run: terraform ${{ github.event.inputs.apply }} -auto-approve -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="hvn_id=hv-personal-${{ env.environment }}" -var="aws_default_region=${{ secrets.AWS_DEFAULT_REGION }}"
 
-  StageHCP:
-    #if: "contains(github.event.head_commit.message, 'build')"
-    name: Deploy HCP
-    needs: [Lint]
-    runs-on: ubuntu-latest
-    env:
-      environment: stg
-      work_dir: ./workspaces/hcp
-    steps:
-      - name: Checkout Repo
-        uses: actions/checkout@v3
-
-      - name: HashiCorp - Setup Terraform
-        uses: hashicorp/setup-terraform@v2.0.0
-        with:
-          terraform_version: 1.2.2
-          cli_config_credentials_token: ${{ secrets.TFC_API_KEY }}
-          terraform_wrapper: false
-        env:
-          TF_WORKSPACE: "hcp-${{ env.environment }}"
-
-      - name: Terraform fmt
-        id: fmt
-        working-directory: ${{ env.work_dir }}
-        run: terraform fmt -check
-        continue-on-error: true
-
-      - name: Terraform Init
-        id: init
-        working-directory: ${{ env.work_dir }}
-        run: terraform init
-
-      - name: Terraform Validate
-        id: validate
-        working-directory: ${{ env.work_dir }}
-        run: terraform validate -no-color
-
-      - name: Terraform Plan
-        id: plan
-        working-directory: ${{ env.work_dir }}
-        run: terraform ${{ github.event.inputs.plan }} -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="hvn_id=hv-personal-${{ env.environment }}" -var="aws_default_region=${{ secrets.AWS_DEFAULT_REGION }}"
-        continue-on-error: false
-
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        working-directory: ${{ env.work_dir}}
-        run: exit 1
-
-      - name: Terraform Apply
-        id: apply
-        working-directory: ${{ env.work_dir }}
-        run: terraform ${{ github.event.inputs.apply }} -auto-approve -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="hvn_id=hv-personal-${{ env.environment }}" -var="aws_default_region=${{ secrets.AWS_DEFAULT_REGION }}"
-
-#  Stg:
-#    name: Deploy Vault Cluster
+#  StageHCP:
+#    #if: "contains(github.event.head_commit.message, 'build')"
+#    name: Deploy HCP
+#    needs: [Lint]
 #    runs-on: ubuntu-latest
-#    needs: [DeployDev]
+#    env:
+#      environment: stg
+#      work_dir: ./workspaces/hcp
 #    steps:
 #      - name: Checkout Repo
 #        uses: actions/checkout@v3
@@ -163,38 +120,87 @@ jobs:
 #          terraform_version: 1.2.2
 #          cli_config_credentials_token: ${{ secrets.TFC_API_KEY }}
 #          terraform_wrapper: false
+#        env:
+#          TF_WORKSPACE: "hcp-${{ env.environment }}"
 #
 #      - name: Terraform fmt
 #        id: fmt
-#        working-directory: ./workspaces/vault_provision
+#        working-directory: ${{ env.work_dir }}
 #        run: terraform fmt -check
 #        continue-on-error: true
 #
 #      - name: Terraform Init
 #        id: init
-#        working-directory: ./workspaces/vault_provision
+#        working-directory: ${{ env.work_dir }}
 #        run: terraform init
 #
 #      - name: Terraform Validate
 #        id: validate
-#        working-directory: ./workspaces/vault_provision
+#        working-directory: ${{ env.work_dir }}
 #        run: terraform validate -no-color
 #
 #      - name: Terraform Plan
 #        id: plan
-#        working-directory: ./workspaces/vault_provision
-#        run: terraform ${{ github.event.inputs.plan }} -no-color -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="tier=dev" -var="vault_cluster_id=${{ secrets.VAULT_CLUSTER_ID }}"
+#        working-directory: ${{ env.work_dir }}
+#        run: terraform ${{ github.event.inputs.plan }} -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="hvn_id=hv-personal-${{ env.environment }}" -var="aws_default_region=${{ secrets.AWS_DEFAULT_REGION }}"
 #        continue-on-error: false
 #
 #      - name: Terraform Plan Status
 #        if: steps.plan.outcome == 'failure'
-#        working-directory: ./workspaces/vault_provision
+#        working-directory: ${{ env.work_dir}}
 #        run: exit 1
 #
 #      - name: Terraform Apply
 #        id: apply
-#        working-directory: ./workspaces/vault_provision
-#        run: terraform ${{ github.event.inputs.apply }} -auto-approve -no-color -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="hvn_id=${{ secrets.HVN_ID }}" -var="aws_default_region=${{ secrets.AWS_DEFAULT_REGION }}"
+#        working-directory: ${{ env.work_dir }}
+#        run: terraform ${{ github.event.inputs.apply }} -auto-approve -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="hvn_id=hv-personal-${{ env.environment }}" -var="aws_default_region=${{ secrets.AWS_DEFAULT_REGION }}"
+#
+##  Stg:
+##    name: Deploy Vault Cluster
+##    runs-on: ubuntu-latest
+##    needs: [DeployDev]
+##    steps:
+##      - name: Checkout Repo
+##        uses: actions/checkout@v3
+##
+##      - name: HashiCorp - Setup Terraform
+##        uses: hashicorp/setup-terraform@v2.0.0
+##        with:
+##          terraform_version: 1.2.2
+##          cli_config_credentials_token: ${{ secrets.TFC_API_KEY }}
+##          terraform_wrapper: false
+##
+##      - name: Terraform fmt
+##        id: fmt
+##        working-directory: ./workspaces/vault_provision
+##        run: terraform fmt -check
+##        continue-on-error: true
+##
+##      - name: Terraform Init
+##        id: init
+##        working-directory: ./workspaces/vault_provision
+##        run: terraform init
+##
+##      - name: Terraform Validate
+##        id: validate
+##        working-directory: ./workspaces/vault_provision
+##        run: terraform validate -no-color
+##
+##      - name: Terraform Plan
+##        id: plan
+##        working-directory: ./workspaces/vault_provision
+##        run: terraform ${{ github.event.inputs.plan }} -no-color -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="tier=dev" -var="vault_cluster_id=${{ secrets.VAULT_CLUSTER_ID }}"
+##        continue-on-error: false
+##
+##      - name: Terraform Plan Status
+##        if: steps.plan.outcome == 'failure'
+##        working-directory: ./workspaces/vault_provision
+##        run: exit 1
+##
+##      - name: Terraform Apply
+##        id: apply
+##        working-directory: ./workspaces/vault_provision
+##        run: terraform ${{ github.event.inputs.apply }} -auto-approve -no-color -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="hvn_id=${{ secrets.HVN_ID }}" -var="aws_default_region=${{ secrets.AWS_DEFAULT_REGION }}"
 
 
 #  Prod:
