Testing GHA with Vault URLs

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -84,14 +84,14 @@ jobs:
         id: secrets
         uses: hashicorp/vault-action@v2.4.1
         with:
-          url: https://4opiad7784.execute-api.us-west-2.amazonaws.com/prod
-          token: ${{ secrets.VAULT_TOKEN }}
+          url: ${{secrets.PRIMARY_VAULT_URL}}
+          token: ${{ secrets.PRIMARY_VAULT_TOKEN }}
           #method: token
           namespace: admin
           extraHeaders: |
-            x-api-key: ${{ secrets.API_KEY }}
+            x-api-key: ${{ secrets.PRIMARY_API_GATEWAY_KEY }}
           secrets: |
-            secret/data/web_app api-key | API-KEY ;
+            secrets/data/web_app url | URL ;
 
       - name: HashiCorp - Setup Terraform
         uses: hashicorp/setup-terraform@v2.0.0
@@ -103,35 +103,35 @@ jobs:
       - name: List files
         run: |
           pwd && ls -la
-          echo "This is API Key: ${{env.API-KEY}}"
+          echo "This is API Key: ${{env.URL}}"
 
-      - name: Terraform fmt
-        id: fmt
-        working-directory: ${{ env.work_dir }}
-        run: pwd && ls -la && terraform fmt -check
-        continue-on-error: true
-
-      - name: Terraform Init
-        id: init
-        working-directory: ${{ env.work_dir }}
-        run: terraform init
-
-      - name: Terraform Validate
-        id: validate
-        working-directory: ${{ env.work_dir }}
-        run: terraform validate -no-color
-
-      - name: Terraform Plan
-        id: plan
-        working-directory: ${{ env.work_dir }}
-        run: terraform ${{ github.event.inputs.plan }} -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="hvn_id=hv-personal-${{ env.environment }}" -var="aws_default_region=${{ secrets.AWS_DEFAULT_REGION }}"
-        continue-on-error: false
-
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        working-directory: ${{ env.work_dir}}
-        run: exit 1
-
+#      - name: Terraform fmt
+#        id: fmt
+#        working-directory: ${{ env.work_dir }}
+#        run: pwd && ls -la && terraform fmt -check
+#        continue-on-error: true
+#
+#      - name: Terraform Init
+#        id: init
+#        working-directory: ${{ env.work_dir }}
+#        run: terraform init
+#
+#      - name: Terraform Validate
+#        id: validate
+#        working-directory: ${{ env.work_dir }}
+#        run: terraform validate -no-color
+#
+#      - name: Terraform Plan
+#        id: plan
+#        working-directory: ${{ env.work_dir }}
+#        run: terraform ${{ github.event.inputs.plan }} -var="hcp_client_id=${{ secrets.HCP_CLIENT_ID }}" -var="hcp_client_secret=${{ secrets.HCP_CLIENT_SECRET }}" -var="hvn_id=hv-personal-${{ env.environment }}" -var="aws_default_region=${{ secrets.AWS_DEFAULT_REGION }}"
+#        continue-on-error: false
+#
+#      - name: Terraform Plan Status
+#        if: steps.plan.outcome == 'failure'
+#        working-directory: ${{ env.work_dir}}
+#        run: exit 1
+#
 #      - name: Terraform Apply
 #        id: apply
 #        working-directory: ${{ env.work_dir }}
